### ISSUE TITLE
Autoupdate and autoclearing downloaded files

### ISSUE THREAD

**Issue by kocane** [ItzDerock/youtube-downloader-website#1]
Thanks for this! Does everything I need and nothing more. Perfect.

Curious - does it keep yt-dlp updated? and is it possible to automatically clear downloaded files or should I do that some other way, like with cron?

**Comment by ItzDerock** [comment]
> Thanks for this! Does everything I need and nothing more. Perfect.

Glad you like it!

> Curious - does it keep yt-dlp updated?

Didn't think of this when making this -- that would probably be a good addition. To update yt-dlp right now, you'll have to drop into a root shell and update using `apk` or rebuild the docker image.

> and is it possible to automatically clear downloaded files or should I do that some other way, like with cron?

It [*should*](https://github.com/ItzDerock/youtube-downloader-website/blob/main/backend/src/downloader.ts#L104) autodelete downloads that are an hour or older, though I haven't really tested this.

**Comment by kocane** [comment]
@ItzDerock if you could make it autoupdate somehow it would of course be a nice addition but doing it once in a while with apk isn't exactly a big obstacle either.

The autodeletion seems to work as it should.

Cheers!

**Comment by ItzDerock** [comment]
> @ItzDerock if you could make it autoupdate somehow it would of course be a nice addition but doing it once in a while with apk isn't exactly a big obstacle either.

This can be done with a cron running the apk command or simply a setInterval in the code.
If I have time I'll add this

**Comment by kocane** [comment]
@ItzDerock Yeah, for now I use `/usr/bin/docker exec -it ytdlp apk upgrade yt-dlp` in cron on my host machine, which is the command to upgrade it, right?
